"""

Game Settings

"""

# customizible settings

FPS = 110

# not customizible settings (can break gameplay if changed)

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
DARK_RED = (10, 0, 0)
GRAY = (150, 150, 150)
GRAY_RED = (150, 100, 100)
GOLD = (255, 215, 0)

HALLWAY_HEIGHT_RATIO = 5
HALLWAY_LOAD_LENGTH = 15

RUNNING = 6
CREDITS = 7

WALL_BASE = 101
WALL_WINDOW = 102
WALL_DOOR = 103
WALL_IMAGE_ONE = 104
WALL_IMAGE_TWO = 105
WALL_ROOM_BASE = 106
WALL_ROOM_BOOK = 107
WALL_ROOM_CLOSET = 108
WALL_ROOM_BED = 109
WALL_ROOM_DOOR = 110
WALL_CLOSET_F = 111
WALL_EXIT = 112

WINDOW_ANIMATION_SPEED = 0.05

CECIL_TERMINAL_VELOCITY = 1
CECIL_ACCELERATION = 0.01
CECIL_FRICTION = 0.001
CECIL_ANIMATION_SPEED = 0.2
CECIL_SPEECH_DELAY = (30, 60)
CECIL_LETTER_ADD_SPEECH = 0.1
CECIL_STAMINA_MAX = 15
CECIL_STAMINA_DRAIN = 0.01

CAMERA_ACCELERATION = 0.8
CAMERA_FRICTION = 0.004

ROOM_PART_AMOUNT = 5

TEXT_DISSAPEAR_TIME = 5
LETTER_ADD_SPEED = 0.05

SCAN_SPEED = 0.4
BLACKOUT_SPEED = 0.1

MIN_DARKNESS = 50
MAX_DARKNESS = 255

THUNDER_COOLDOWN = (30, 300)
THUNDER_BLINK_LENGTH = 0.2

VISIBILE_TRANSPARENCY = 250

PARALYZE_BEFORE_KILL_WAIT = 2
PARALYZE_KILL_WAIT = 3
PARALYZE_DISSAPEAR_TIME = 0.5
PARALYZE_SPEECH = 'PLEASE MOVE'
PARALYZE_LETTER_ADD_SPEED = 0.001
PARALYZE_SPAWN_CHANCE = 15 # 30

FISHERMAN_FADING_TIME = 1
FISHERMAN_DISSAPEAR_TIME = 20
FISHERMAN_JUMPSCARE_LENGTH = 3
FISHERMAN_SPEECH = 'I smell your guts'
FISHERMAN_LETTER_ADD_SPEED = 0.001
FISHERMAN_SPAWN_CHANCE = 15 # 30

MIMIC_FADING_TIME = 1
MIMIC_JUMPSCARE_LENGTH = 3
MIMIC_SPEECH = 'let\'s play Cecil!'
MIMIC_CHASE_LENGTH = 6.5
MIMIC_LETTER_ADD_SPEED = 0.001
MIMIC_BEFORE_TRIGGER_TIMER = 1
MIMIC_SPAWN_CHANCE = 15 # 30
MIMIC_ACCELERATION = 0.0005

CREDITS_LETTER_ADD_SPEED = 0.1
CREDITS_TEXT = [
    '...',
    'Thank You for playing our game!',
    'This game was made by rdmchik and stacil',
    'If you died in the first 5 minutes of the game',
    'There is still a lot to explore.',
    'Find your way out!',
    'All of the sounds used in the game are royality free',
    'All of the images and sprites in the game are created by stacil',
    'All of the code is written by rdmchik',
    'Only pure python was used to make this game!'
    'Game was created for pygame 2022 halloween jam',
    '...'
]

LIGHTING_SHADER_INITIAL_DEPTH = 10
FIND_OBJECT_CHANCE = 2

NARRATOR_LETTER_ADD_SPEED = 0.001

MARATHONER_ANIMATION_SPEED = 0.05
MARATHONER_ACCELERATION = 99
MARATHONER_SPAWN_CHANCE = 15
MARATHONER_BEFORE_MOVE_TIME = 7
