"""

Game Settings

"""

# customizible settings

FPS = 110

# not customizible settings

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
DARK_RED = (10, 0, 0)

HALLWAY_HEIGHT_RATIO = 5
HALLWAY_LOAD_LENGTH = 200

TUTORIAL_BEGINING = 0
TUTORIAL_PARALYZE = 1
TUTORIAL_FISHERMAN = 2
TUTORIAL_MIMIC = 3
TUTORIAL_MARATHON = 4
POST_TUTORIAL = 5
ENDING = 6
CREDITS = 7

WALL_BASE = 101
WALL_WINDOW = 102

CECIL_TERMINAL_VELOCITY = 1
CECIL_ACCELERATION = 0.01
CECIL_FRICTION = 0.001
CECIL_ANIMATION_SPEED = 0.2
CECIL_SPEECH_DELAY = (30, 200)
CECIL_LETTER_ADD_SPEECH = 0.1

CAMERA_ACCELERATION = 0.8
CAMERA_FRICTION = 0.004

TEXT_DISSAPEAR_TIME = 2
LETTER_ADD_SPEED = 0.05

SCAN_SPEED = 0.4
BLACKOUT_SPEED = 0.1

MIN_DARKNESS = 100
MAX_DARKNESS = 255

THUNDER_COOLDOWN = (30, 60)
THUNDER_BLINK_LENGTH = 0.2

VISIBILE_TRANSPARENCY = 250

PARALYZE_BEFORE_KILL_WAIT = 1
PARALYZE_KILL_WAIT = 1
PARALYZE_DISSAPEAR_TIME = 0.5
PARALYZE_SPEECH = '[????????] DON\'T MOVE DON\'T MOVE DON\'T MOVE DON\'T MOVE'
PARALYZE_LETTER_ADD_SPEED = 0.001


